obj-y += vssim_config_manager.o
obj-y += ftl.o ftl_mapping_manager.o ftl_inverse_mapping_manager.o
obj-y += ftl_gc_manager.o ftl_perf_manager.o ftl_cache.o
obj-y += ssd.o ssd_trim_manager.o ssd_log_manager.o ssd_io_manager.o
obj-y += firm_buffer_manager.o

# Added by SSLab.
obj-y += hmb.o hmb_debug.o hmb_internal.o hmb_spaceMgmt.o hmb_utils.o hmb_fastIO.o
